//! Generator entry-point. `Generate::run("hosts" | "users" | "network" | …)`
//! turns the loaded [`Configuration`] into a `var/generated/*.nix` file.
//!
//! Each section produces a [`NixAttrSet`] / [`NixList`] tree which is rendered
//! via the `Display` impl on the `token::*` types and then formatted with
//! `nixfmt -sv`. The file content is purposely fully deterministic so diffs
//! between runs reflect actual config changes only.

use std::collections::{BTreeSet, HashSet};
use std::path::{Path, PathBuf};

use indexmap::IndexMap;
use regex::Regex;

use crate::error::{NixError, Result};
use crate::nix_generator::configuration::Configuration;
use crate::nix_generator::item::host::{Host, ServiceParams};
use crate::nix_generator::nix_builder::array_to_nix;
use crate::nix_generator::nix_service::{NixService, ServiceRegistry};
use crate::nix_generator::nix_zone::{NixZone, EXTERNAL_ZONE_KEY};
use crate::nix_generator::schema::{Coordination, FleetUpdate, Matrix, NetworkDefault, Smtp};
use crate::nix_generator::token::{NixAttrSet, NixList};
use crate::nix_generator::validation::TIMEOUT_KEYS;

const GEN_FILE_HEADER: &str = "# This file is generated by 'just generate' or 'just clean'\n# from the configuration file etc/config.yaml\n# --> DO NOT EDIT <--\n\n";

pub struct Generate {
    config: Configuration,
    project_root: PathBuf,
}

impl Generate {
    pub fn new(main_yaml: &Path, generated_yaml: &Path, registry: ServiceRegistry) -> Result<Self> {
        let project_root = main_yaml
            .parent()
            .and_then(|p| p.parent())
            .ok_or_else(|| NixError::generate("Cannot determine project root from YAML path"))?
            .to_path_buf();

        let config = Configuration::load(main_yaml, generated_yaml, registry)?;
        Ok(Self {
            config,
            project_root,
        })
    }

    pub fn run(&self, command: &str) -> Result<String> {
        match command {
            "hosts" => self.generate_hosts(),
            "users" => self.generate_users(),
            "network" => self.generate_network(),
            "machines" => self.generate_machines(),
            "doc" => self.generate_doc(),
            other => Err(NixError::generate(format!("Unknown command: {other}"))),
        }
    }

    // ─── hosts.nix ──────────────────────────────────────────────────────────

    fn generate_hosts(&self) -> Result<String> {
        let content = self.generate_hosts_raw()?;
        let target = self.project_root.join("var/generated/hosts.nix");
        write_and_format(&target, &content)
    }

    pub fn generate_hosts_raw(&self) -> Result<String> {
        let mut list = NixList::new();
        for host in self.config.hosts.values() {
            list.add(Box::new(build_host_attrs(host)));
        }
        Ok(format!("{GEN_FILE_HEADER}{list}"))
    }

    // ─── users.nix ──────────────────────────────────────────────────────────

    fn generate_users(&self) -> Result<String> {
        let content = self.generate_users_raw()?;
        self.seed_user_overlays()?;
        let target = self.project_root.join("var/generated/users.nix");
        write_and_format(&target, &content)
    }

    /// Seed `usr/users/<login>/default.nix` for every declared login (the
    /// implicit `nix` account included). The framework imports that path
    /// unconditionally, so a missing directory fails the evaluation with a bare
    /// `path does not exist`. Seeded once, then owned by the user.
    fn seed_user_overlays(&self) -> Result<()> {
        for user in self.config.users.values() {
            let user_dir = self.project_root.join("usr/users").join(&user.login);
            let target = user_dir.join("default.nix");
            seed_if_missing(&target, || {
                std::fs::create_dir_all(&user_dir)?;
                let profile = user.profile.rsplit('/').next().unwrap_or(&user.profile);
                std::fs::write(
                    &target,
                    format!(
                        "# Home manager overlay of {} (profile: {profile}).\n\n{{ }}\n",
                        user.login
                    ),
                )
            })?;
        }
        Ok(())
    }

    pub fn generate_users_raw(&self) -> Result<String> {
        let mut outer = NixAttrSet::new();
        let domain = &self.config.network.config.domain;

        for user in self.config.users.values() {
            let mut attrs = NixAttrSet::new();
            let email = user
                .email
                .clone()
                .unwrap_or_else(|| format!("{}@{}", user.login, domain));

            attrs.set_int("uid", user.uid as i64);
            attrs.set_string("email", &email);
            attrs.set_string("name", &user.name);
            attrs.set_string("profile", &user.profile);
            attrs.set("groups", Box::new(NixList::from_strings(&user.groups)));
            if user.disabled {
                attrs.set_bool("disabled", true);
            }

            outer.set(&user.login, Box::new(attrs));
        }

        Ok(format!("{GEN_FILE_HEADER}{outer}"))
    }

    // ─── network.nix ────────────────────────────────────────────────────────

    fn generate_network(&self) -> Result<String> {
        let content = self.generate_network_raw()?;

        // Actionable, never fatal: a zone can run without its own cache.
        for zone in self.config.network.zones_without_harmonia() {
            eprintln!(
                "WARN: zone '{zone}' has no harmonia service: everything the fleet builds for it travels host by host. Declare 'harmonia:' on one of its hosts."
            );
        }
        let target = self.project_root.join("var/generated/network.nix");
        write_and_format(&target, &content)
    }

    pub fn generate_network_raw(&self) -> Result<String> {
        let cfg = &self.config.network.config;
        let mut outer = NixAttrSet::new();
        outer.set_string("domain", &cfg.domain);

        // Verbatim blocks: only the keys actually present in config.yaml are
        // emitted, in declaration order.
        if let Some(d) = &cfg.default {
            outer.set("default", Box::new(build_network_default(d)));
        }
        if let Some(c) = &cfg.coordination {
            outer.set("coordination", Box::new(build_network_coordination(c)));
        }
        if let Some(s) = &cfg.smtp {
            outer.set("smtp", Box::new(build_network_smtp(s)));
        }
        if let Some(m) = &cfg.matrix {
            outer.set("matrix", Box::new(build_network_matrix(m)));
        }
        if let Some(fu) = &cfg.fleet_update {
            outer.set("fleetUpdate", Box::new(build_network_fleet_update(fu)));
        }

        // services list (declaration order)
        let mut services_list = NixList::new();
        for svc in self.config.network.services_as_vec() {
            services_list.add(Box::new(build_service_attrs(svc)));
        }
        outer.set("services", Box::new(services_list));

        // zones (sorted by name for deterministic output)
        let mut zones_attrs = NixAttrSet::new();
        let mut zone_names: Vec<&str> = self
            .config
            .network
            .zones
            .keys()
            .map(String::as_str)
            .collect();
        zone_names.sort();
        for zone_name in zone_names {
            let zone = &self.config.network.zones[zone_name];
            zones_attrs.set(zone_name, Box::new(self.build_zone_nix(zone)));
        }
        outer.set("zones", Box::new(zones_attrs));

        Ok(format!("{GEN_FILE_HEADER}{outer}"))
    }

    fn build_zone_nix(&self, zone: &NixZone) -> NixAttrSet {
        let mut attrs = NixAttrSet::new();

        // All zone config fields go through verbatim, sorted for stability.
        let mut config_keys: Vec<&str> = zone.config.keys().map(String::as_str).collect();
        config_keys.sort();
        for key in config_keys {
            if let Some(val) = zone.config.get(key) {
                attrs.set(key, array_to_nix(val));
            }
        }
        attrs.set_string("name", &zone.name);

        if zone.is_external() {
            attrs.set(
                "tls-builder-hosts",
                Box::new(self.compute_tls_builder_hosts()),
            );
            attrs.set("external-hosts", Box::new(self.compute_external_hosts()));
            let unbound_data = self.compute_unbound_local_data(zone);
            if !unbound_data.is_empty() {
                let mut unbound = NixAttrSet::new();
                unbound.set("local-data", Box::new(NixList::from_strings(unbound_data)));
                attrs.set("unbound", Box::new(unbound));
            }
        } else {
            attrs.set(
                "extraDnsmasqSettings",
                Box::new(self.compute_extra_dnsmasq(zone)),
            );
            attrs.set("roaming", Box::new(build_roaming_attrs(zone)));
        }

        attrs
    }

    fn compute_extra_dnsmasq(&self, zone: &NixZone) -> NixAttrSet {
        let mut settings = NixAttrSet::new();

        // dhcp-host: sorted MAC entries (stable diffs), native hosts first then
        // the reservations held for hosts visiting from another zone.
        let mut dhcp_entries: Vec<String> = zone.mac_addresses().values().cloned().collect();
        dhcp_entries.extend(
            zone.roaming()
                .values()
                .map(|(mac, ip)| format!("{mac},{ip}")),
        );
        dhcp_entries.sort();
        settings.set("dhcp-host", Box::new(NixList::from_strings(dhcp_entries)));

        settings.set(
            "dhcp-range",
            Box::new(NixList::from_strings(&zone.dhcp_range)),
        );

        // address: /<zone.domain>/<gateway-lan-ip>
        let mut address = NixList::new();
        if let Some(gw_ip) = zone.gateway_lan_ip() {
            address.add_string(format!("/{}/{}", zone.domain(), gw_ip));
        }
        settings.set("address", Box::new(address));

        settings.set("server", Box::new(self.compute_dnsmasq_server(zone)));
        settings.set(
            "host-record",
            Box::new(NixList::from_strings(self.compute_host_records(zone))),
        );

        settings
    }

    /// dnsmasq `server=` list for a local zone:
    /// 1. external zone first (network.domain → www gateway VPN IP),
    /// 2. then every other local zone in alphabetical order, mapping the
    ///    zone's domain to its LAN gateway IP.
    fn compute_dnsmasq_server(&self, zone: &NixZone) -> NixList {
        let network_domain = &self.config.network.config.domain;
        let mut server = NixList::new();
        if let Some(www) = self.config.network.zones.get(EXTERNAL_ZONE_KEY) {
            if let Some(vpn_ip) = www.gateway_vpn_ipv4() {
                server.add_string(format!("/{network_domain}/{vpn_ip}"));
            }
        }
        let mut other_locals: Vec<&str> = self
            .config
            .network
            .zones
            .keys()
            .filter(|n| n.as_str() != EXTERNAL_ZONE_KEY && *n != &zone.name)
            .map(String::as_str)
            .collect();
        other_locals.sort();
        for other_name in other_locals {
            if let Some(other) = self.config.network.zones.get(other_name) {
                if let Some(gw_ip) = other.gateway_lan_ip() {
                    server.add_string(format!("/{}/{}", other.domain(), gw_ip));
                }
            }
        }
        server
    }

    /// Build the `host-record` list for `zone`:
    /// 1. globally registered host records (one per declared host's main IP),
    /// 2. service records (zone-local, external, reverse-proxied),
    /// 3. aliases of the current zone,
    /// 4. aliases of the external (`www`) zone replicated using LOCAL IPs,
    /// 5. residual hosts from `zone.hosts()` not yet emitted (extraHosts etc.),
    /// 6. roaming hosts, under this zone's domain only,
    /// 7. final lexicographic sort.
    fn compute_host_records(&self, zone: &NixZone) -> Vec<String> {
        let network_domain = &self.config.network.config.domain;
        let mut entries: Vec<String> = self.config.host_records.clone();

        // Step 2 — services
        for svc in self.config.network.services_as_vec() {
            let svc_zone = self.config.network.zones.get(&svc.zone);
            let host_ip = self
                .config
                .hosts
                .get(&svc.host)
                .and_then(|h| h.ip.as_deref());

            if svc.zone == EXTERNAL_ZONE_KEY {
                // www: only external-access services are reachable from the LAN.
                if self
                    .config
                    .network
                    .registry
                    .flags(&svc.name)
                    .external_access
                {
                    if let Some(ip) = host_ip {
                        let fqdn = svc.fqdn(
                            svc_zone.map(|z| z.domain()).unwrap_or(network_domain),
                            network_domain,
                        );
                        entries.push(format!("{fqdn},{ip}"));
                    }
                }
            } else if let Some(svc_zone_ref) = svc_zone {
                // Reverse-proxied services share the gateway's IP; everything
                // else points at the host's own IP.
                let ip = if self.config.network.registry.flags(&svc.name).reverse_proxy {
                    svc_zone_ref.gateway_lan_ip().map(str::to_string)
                } else {
                    host_ip.map(str::to_string)
                };
                let fqdn = svc.fqdn(svc_zone_ref.domain(), network_domain);
                if let Some(ip) = ip {
                    if svc.zone == zone.name {
                        entries.push(format!("{},{fqdn},{ip}", svc.domain_label()));
                    } else {
                        entries.push(format!("{fqdn},{ip}"));
                    }
                }
            }
        }

        // Step 3 — aliases of the current zone
        for (host, aliases) in zone.aliases() {
            if let Some(Some(ip)) = zone.hosts().get(host) {
                for alias in aliases {
                    entries.push(format!("{alias},{alias}.{},{ip}", zone.domain()));
                }
            }
        }

        // Step 4 — www aliases replicated with LOCAL IP (looked up in the
        // current zone's hosts, not www's).
        if let Some(www) = self.config.network.zones.get(EXTERNAL_ZONE_KEY) {
            for (host, aliases) in www.aliases() {
                if let Some(Some(ip)) = zone.hosts().get(host) {
                    for alias in aliases {
                        entries.push(format!("{alias},{alias}.{network_domain},{ip}"));
                    }
                }
            }
        }

        // Step 5 — residual hosts (de-duplicated against the shortname — the
        // first comma-separated field — of already-emitted records).
        let already: std::collections::HashSet<String> = entries
            .iter()
            .filter_map(|e| e.split(',').next().map(str::to_string))
            .collect();
        let mut residual: Vec<(&String, &String)> = zone
            .hosts()
            .iter()
            .filter_map(|(h, ip)| ip.as_ref().map(|i| (h, i)))
            .filter(|(h, _)| !already.contains(h.as_str()))
            .collect();
        residual.sort_by(|a, b| a.0.cmp(b.0));
        for (host, ip) in residual {
            entries.push(format!("{host},{host}.{},{ip}", zone.domain()));
        }

        // Step 6 — roaming hosts. Fully-qualified under the visited zone only:
        // the short name keeps pointing at the host's home address, so adding
        // these records never shadows an existing one.
        for (host, (_, ip)) in zone.roaming() {
            entries.push(format!("{host}.{},{ip}", zone.domain()));
        }

        entries.sort();
        entries
    }

    /// `tls-builder-hosts`: non-global LAN services whose TLS cert is built on
    /// the HCS (public ACME) and synced to the gateway, formatted as
    /// `<service-domain>.<zone-domain>`. The HCS serves a stub `respond` vhost
    /// just to trigger cert issuance.
    ///
    /// `externalAccess` services are excluded: they get a real reverse-proxy
    /// vhost on the HCS instead (see `compute_external_hosts`), which builds
    /// the very same cert while also exposing the service.
    fn compute_tls_builder_hosts(&self) -> NixList {
        let mut list = NixList::new();
        for svc in self.config.network.services_as_vec() {
            if svc.zone == EXTERNAL_ZONE_KEY || svc.global {
                continue;
            }
            if self
                .config
                .network
                .registry
                .flags(&svc.name)
                .external_access
            {
                continue;
            }
            if let Some(svc_zone) = self.config.network.zones.get(&svc.zone) {
                list.add_string(format!("{}.{}", svc.domain_label(), svc_zone.domain()));
            }
        }
        list
    }

    /// `external-hosts`: non-global zone services flagged `externalAccess`.
    /// The HCS terminates public TLS for each FQDN and reverse-proxies it to
    /// the service's zone gateway over the tailnet; the gateway's own vhost
    /// then handles SSO and the real backend. Each entry ships the target
    /// gateway VPN IP so the Nix side needs no zone lookup:
    /// `{ fqdn = "<svc>.<zone-domain>"; target = "<gateway-vpn-ipv4>"; }`.
    fn compute_external_hosts(&self) -> NixList {
        let mut list = NixList::new();
        for svc in self.config.network.services_as_vec() {
            if svc.zone == EXTERNAL_ZONE_KEY || svc.global {
                continue;
            }
            if !self
                .config
                .network
                .registry
                .flags(&svc.name)
                .external_access
            {
                continue;
            }
            let Some(svc_zone) = self.config.network.zones.get(&svc.zone) else {
                continue;
            };
            let Some(target) = svc_zone.gateway_vpn_ipv4() else {
                continue;
            };
            let mut entry = NixAttrSet::new();
            entry.set_string(
                "fqdn",
                format!("{}.{}", svc.domain_label(), svc_zone.domain()),
            );
            entry.set_string("target", target);
            list.add(Box::new(entry));
        }
        list
    }

    /// Unbound `local-data` block for the www zone — synthesises A records for
    /// every global service so the upstream resolver answers with the VPN IP.
    fn compute_unbound_local_data(&self, www_zone: &NixZone) -> Vec<String> {
        let network_domain = &self.config.network.config.domain;
        let Some(vpn_ip) = www_zone.gateway_vpn_ipv4() else {
            return vec![];
        };
        let mut entries = vec![];
        for svc in self.config.network.services_as_vec() {
            if svc.zone != EXTERNAL_ZONE_KEY || !svc.global {
                continue;
            }
            if self
                .config
                .network
                .registry
                .flags(&svc.name)
                .external_access
            {
                continue;
            }
            entries.push(format!(
                "\"{}.{}. IN A {vpn_ip}\"",
                svc.domain_label(),
                network_domain
            ));
        }
        entries.sort();
        entries
    }

    // ─── machines ───────────────────────────────────────────────────────────

    /// Lay down `usr/machines/<host>/` for hosts with a disko profile, then
    /// write `var/generated/hosts/<host>.nix` for hosts with `install/disko.nix`.
    ///
    /// - `configuration.nix`: seeded once, then owned by the user.
    /// - `install/disko.nix`: follows `etc/config.yaml` until the host is
    ///   sealed by `install/state.nix` (`just install`), frozen afterwards.
    /// - `var/generated/hosts/*.nix` not written by this run are removed.
    fn generate_machines(&self) -> Result<String> {
        let template_src = self
            .project_root
            .join("dnf/hosts/templates/usr-machines-configuration.nix");
        let hosts_dir = self.project_root.join("var/generated/hosts");
        let mut written = HashSet::new();

        for host in self.config.hosts.values() {
            let machine_dir = self.project_root.join("usr/machines").join(&host.hostname);
            let install_dir = machine_dir.join("install");
            let disko_dst = install_dir.join("disko.nix");

            if let Some(ref profile_path) = host.disko.profile {
                std::fs::create_dir_all(&install_dir)?;
                seed_if_missing(&machine_dir.join("configuration.nix"), || {
                    std::fs::copy(&template_src, machine_dir.join("configuration.nix")).map(|_| ())
                })?;

                // Sealed host: the disk was formatted with this file, only a
                // deliberate deletion brings the profile back.
                let sealed = install_dir.join("state.nix").exists();
                if !sealed || !disko_dst.exists() {
                    let profile = std::fs::read_to_string(self.project_root.join(profile_path))?;
                    let content = build_install_disko(host, profile_path, &profile)?;
                    write_and_format(&disko_dst, &content)?;
                }
            }

            if !disko_dst.exists() {
                continue;
            }
            let body = build_generated_conf_body(&std::fs::read_to_string(&disko_dst)?);
            if body.is_empty() {
                continue;
            }
            let target = hosts_dir.join(format!("{}.nix", host.hostname));
            write_and_format(&target, &format!("{GEN_FILE_HEADER}{{lib,...}}:{{{body}}}"))?;
            written.insert(target);
        }

        remove_unwritten_nix_files(&hosts_dir, &written)?;
        Ok(String::new())
    }

    // ─── docs ───────────────────────────────────────────────────────────────

    fn generate_doc(&self) -> Result<String> {
        crate::mdx_generator::generator::generate(&self.project_root, false)
    }
}

/// `zone.roaming`: hostname -> address this zone reserves for that host while
/// it is plugged here instead of at home. Consumed by the install tooling to
/// target a machine outside its own zone; dnsmasq gets the same data through
/// `dhcp-host` / `host-record`.
fn build_roaming_attrs(zone: &NixZone) -> NixAttrSet {
    let mut attrs = NixAttrSet::new();
    for (host, (_, ip)) in zone.roaming() {
        attrs.set_string(host, ip);
    }
    attrs
}

// ─── per-host hosts.nix builder ────────────────────────────────────────────

/// Build one entry of the `hosts.nix` list — the full data structure shared
/// with the rest of the framework (modules, flake, colmena, etc.).
fn build_host_attrs(host: &Host) -> NixAttrSet {
    let mut attrs = NixAttrSet::new();

    attrs.set_string("hostname", &host.hostname);
    attrs.set_string("zone", &host.zone);
    attrs.set_string("fqdn", format!("{}.{}", host.hostname, host.zone_domain));
    attrs.set_string("name", &host.name);
    attrs.set_string("profile", &host.profile);

    if let Some(ip) = &host.ip {
        attrs.set_string("ip", ip);
    }
    if let Some(vpn_ip) = &host.vpn_ip {
        attrs.set_string("vpnIp", vpn_ip);
    }
    if let Some(arch) = &host.arch {
        attrs.set_string("arch", arch);
    }

    attrs.set_string("zoneDomain", &host.zone_domain);
    attrs.set_string("networkDomain", &host.network_domain);

    attrs.set("groups", Box::new(NixList::from_strings(&host.groups)));

    // features: key → value (defaults to the host's zone name)
    let mut features = NixAttrSet::new();
    for (k, v) in &host.features {
        features.set_string(k, v);
    }
    attrs.set("features", Box::new(features));

    attrs.set("users", Box::new(NixList::from_strings(&host.users)));
    attrs.set("colmena", Box::new(build_colmena(host)));
    attrs.set("services", Box::new(build_host_services(&host.services)));

    attrs
}

/// `colmena.deployment.tags` aggregates host-tagged metadata: explicit tags,
/// group/feature/user/zone derivations.
fn build_colmena(host: &Host) -> NixAttrSet {
    let mut tags = NixList::new();
    for t in &host.tags {
        tags.add_string(t);
    }
    for g in &host.groups {
        tags.add_string(format!("group-{g}"));
    }
    for k in host.features.keys() {
        tags.add_string(format!("feature-{k}"));
    }
    for u in &host.users {
        if u != "nix" {
            tags.add_string(format!("user-{u}"));
        }
    }
    tags.add_string(format!("zone-{}", host.zone));

    let mut deployment = NixAttrSet::new();
    deployment.set("tags", Box::new(tags));
    let mut colmena = NixAttrSet::new();
    colmena.set("deployment", Box::new(deployment));
    colmena
}

fn build_host_services(services: &IndexMap<String, ServiceParams>) -> NixAttrSet {
    let mut out = NixAttrSet::new();
    for (svc_name, params) in services {
        let mut svc = NixAttrSet::new();
        if let Some(title) = &params.title {
            svc.set_string("title", title);
        }
        if let Some(desc) = &params.description {
            svc.set_string("description", desc);
        }
        if let Some(domain) = &params.domain {
            svc.set_string("domain", domain);
        }
        if params.global {
            svc.set_bool("global", true);
        }
        out.set(svc_name, Box::new(svc));
    }
    out
}

// ─── network.nix verbatim block builders ────────────────────────────────────

fn build_network_default(d: &NetworkDefault) -> NixAttrSet {
    let mut attrs = NixAttrSet::new();
    if let Some(locale) = &d.locale {
        attrs.set_string("locale", locale);
    }
    if let Some(tz) = &d.timezone {
        attrs.set_string("timezone", tz);
    }
    attrs
}

fn build_network_coordination(c: &Coordination) -> NixAttrSet {
    let mut attrs = NixAttrSet::new();
    if let Some(enable) = c.enable {
        attrs.set_bool("enable", enable);
    }
    if let Some(hostname) = &c.hostname {
        attrs.set_string("hostname", hostname);
    }
    if let Some(domain) = &c.domain {
        attrs.set_string("domain", domain);
    }
    attrs
}

fn build_network_smtp(s: &Smtp) -> NixAttrSet {
    let mut attrs = NixAttrSet::new();
    if let Some(protocol) = &s.protocol {
        attrs.set_string("protocol", protocol);
    }
    if let Some(server) = &s.server {
        attrs.set_string("server", server);
    }
    if let Some(port) = s.port {
        attrs.set_int("port", port as i64);
    }
    if let Some(username) = &s.username {
        attrs.set_string("username", username);
    }
    if let Some(sender) = &s.sender {
        attrs.set_string("sender", sender);
    }
    if let Some(tls) = s.tls {
        attrs.set_bool("tls", tls);
    }
    attrs
}

fn build_network_matrix(m: &Matrix) -> NixAttrSet {
    let mut attrs = NixAttrSet::new();
    if let Some(admins) = &m.admins {
        let mut list = NixList::new();
        for admin in admins {
            list.add_string(admin);
        }
        attrs.set("admins", Box::new(list));
    }
    attrs
}

fn build_network_fleet_update(fu: &FleetUpdate) -> NixAttrSet {
    let mut attrs = NixAttrSet::new();
    if let Some(order) = &fu.deployment_order {
        attrs.set_string("deploymentOrder", order);
    }
    if let Some(critical) = &fu.critical_profiles {
        attrs.set_string("criticalProfiles", critical);
    }
    if let Some(model) = &fu.ai_model {
        attrs.set_string("aiModel", model);
    }

    // `TIMEOUT_KEYS` order, not the YAML's: reordering the config must not
    // diff the generated file.
    if let Some(declared) = &fu.timeouts {
        let mut timeouts = NixAttrSet::new();
        for key in TIMEOUT_KEYS {
            if let Some(seconds) = declared.get(*key) {
                timeouts.set_int(*key, *seconds);
            }
        }
        attrs.set("timeouts", Box::new(timeouts));
    }
    if let Some(interval) = fu.ping_interval {
        attrs.set_int("pingInterval", interval);
    }
    attrs
}

// ─── network.nix service entry builder ──────────────────────────────────────

fn build_service_attrs(svc: &NixService) -> NixAttrSet {
    let mut attrs = NixAttrSet::new();
    attrs.set_string("name", &svc.name);
    if let Some(d) = &svc.domain {
        attrs.set_string("domain", d);
    }
    attrs.set_string("host", &svc.host);
    attrs.set_string("zone", &svc.zone);
    if let Some(t) = &svc.title {
        attrs.set_string("title", t);
    }
    if let Some(d) = &svc.description {
        attrs.set_string("description", d);
    }
    if svc.global {
        attrs.set_bool("global", true);
    }
    attrs
}

// ─── disko helpers ──────────────────────────────────────────────────────────

/// Token a disko profile puts in place of each disk path, replaced from
/// `disko.devices` of `etc/config.yaml` when `install/disko.nix` is written.
const RE_DEVICE_TOKEN: &str = r"@DEVICE:([^@\s]*)@";

/// `install/disko.nix`: provenance header, then the profile with every
/// `@DEVICE:<disk>@` token replaced. Fail-closed: a default disk path could
/// format the wrong drive, so tokens and declared devices must match exactly.
fn build_install_disko(host: &Host, profile_path: &str, profile: &str) -> Result<String> {
    let re = Regex::new(RE_DEVICE_TOKEN).expect("Invalid regex pattern");
    let devices = &host.disko.devices;
    let hostname = &host.hostname;

    let tokens: BTreeSet<&str> = re
        .captures_iter(profile)
        .filter_map(|c| c.get(1).map(|m| m.as_str()))
        .collect();
    let missing: Vec<&str> = tokens
        .iter()
        .copied()
        .filter(|t| !devices.contains_key(*t))
        .collect();
    if !missing.is_empty() {
        return Err(NixError::validation(format!(
            "Host '{hostname}': no disko device for disk(s) {} of {profile_path} (etc/config.yaml: disko.devices)",
            missing.join(", ")
        )));
    }
    let mut unused: Vec<&str> = devices
        .keys()
        .map(String::as_str)
        .filter(|d| !tokens.contains(d))
        .collect();
    unused.sort_unstable();
    if !unused.is_empty() {
        return Err(NixError::validation(format!(
            "Host '{hostname}': disko device(s) {} have no @DEVICE:<disk>@ token in {profile_path}",
            unused.join(", ")
        )));
    }

    let layout = re.replace_all(profile, |caps: &regex::Captures| devices[&caps[1]].clone());
    if layout.contains("@DEVICE:") {
        return Err(NixError::validation(format!(
            "Host '{hostname}': malformed @DEVICE:<disk>@ token left in {profile_path}"
        )));
    }

    let mut pairs: Vec<String> = devices.iter().map(|(d, p)| format!("{d}={p}")).collect();
    pairs.sort();
    let origin = if pairs.is_empty() {
        profile_path.to_string()
    } else {
        format!("{profile_path} ({})", pairs.join(", "))
    };
    Ok(format!(
        "# Disk layout of {hostname}, frozen at install\n\
         #\n\
         # From {origin}.\n\
         # Rewritten by 'just generate' until install/state.nix exists ('just install'),\n\
         # then never: the disk was formatted with it.\n\n\
         {layout}"
    ))
}

/// Flags inferred from `install/disko.nix` that disko does not set itself.
/// Empty when the layout needs none.
fn build_generated_conf_body(disko_content: &str) -> String {
    let mut body = String::new();

    if disko_content.contains("type = \"mdadm\";") {
        body.push_str("boot.swraid.enable = lib.mkForce true;");
    }

    // Honour `# NEEDEDFORBOOT:<mountpoint>;<mountpoint>` markers in disko files.
    for line in disko_content.lines() {
        if let Some(rest) = line.strip_prefix("# NEEDEDFORBOOT:") {
            for partition in rest.split(';') {
                let p = partition.trim();
                if !p.is_empty() {
                    body.push_str(&format!(
                        "fileSystems.\"{p}\".neededForBoot=lib.mkForce true;"
                    ));
                }
            }
        }
    }

    body
}

/// Remove the `*.nix` files of `dir` this run did not write: host gone from
/// `etc/config.yaml`, without `install/disko.nix`, or nothing left to force.
fn remove_unwritten_nix_files(dir: &Path, written: &HashSet<PathBuf>) -> Result<()> {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return Ok(());
    };
    for entry in entries {
        let path = entry?.path();
        let is_nix = path.extension().is_some_and(|ext| ext == "nix");
        if is_nix && path.is_file() && !written.contains(&path) {
            std::fs::remove_file(&path)?;
        }
    }
    Ok(())
}

fn seed_if_missing<F>(path: &Path, write: F) -> Result<()>
where
    F: FnOnce() -> std::io::Result<()>,
{
    if path.exists() {
        return Ok(());
    }
    write()?;
    Ok(())
}

// ─── output ─────────────────────────────────────────────────────────────────

/// Write `content` to `target`, then run `nixfmt -sv` on it (best-effort —
/// formatter failures don't fail the generator).
fn write_and_format(target: &Path, content: &str) -> Result<String> {
    // A fresh workspace (boilerplate clone) has no `var/generated/` yet: create
    // the destination rather than failing with a bare ENOENT.
    if let Some(parent) = target.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(target, content)?;
    let _ = std::process::Command::new("nixfmt")
        .arg("-sv")
        .arg(target)
        .status();
    Ok(String::new())
}
