//! Generator entry-point. `Generate::run("hosts" | "users" | "network" | …)`
//! turns the loaded [`Configuration`] into a `var/generated/*.nix` file.
//!
//! Each section produces a [`NixAttrSet`] / [`NixList`] tree which is rendered
//! via the `Display` impl on the `token::*` types and then formatted with
//! `nixfmt -sv`. The file content is purposely fully deterministic so diffs
//! between runs reflect actual config changes only.

use std::path::{Path, PathBuf};

use indexmap::IndexMap;

use crate::error::{NixError, Result};
use crate::nix_generator::configuration::Configuration;
use crate::nix_generator::item::host::{DiskoConfig, Host, ServiceParams};
use crate::nix_generator::nix_builder::array_to_nix;
use crate::nix_generator::nix_service::{
    NixService, EXTERNAL_ACCESS_SERVICES, REVERSE_PROXY_SERVICES,
};
use crate::nix_generator::nix_zone::{NixZone, EXTERNAL_ZONE_KEY};
use crate::nix_generator::token::{NixAttrSet, NixList};

const GEN_FILE_HEADER: &str = "# This file is generated by 'just generate' or 'just clean'\n# from the configuration file usr/config.yaml\n# --> DO NOT EDIT <--\n\n";

/// Top-level network keys copied verbatim from YAML into `network.nix`.
const NETWORK_PASSTHROUGH_KEYS: &[&str] = &["default", "coordination", "smtp"];

pub struct Generate {
    config: Configuration,
    project_root: PathBuf,
}

impl Generate {
    pub fn new(main_yaml: &Path, generated_yaml: &Path) -> Result<Self> {
        let project_root = main_yaml
            .parent()
            .and_then(|p| p.parent())
            .ok_or_else(|| NixError::generate("Cannot determine project root from YAML path"))?
            .to_path_buf();

        let config = Configuration::load(main_yaml, generated_yaml)?;
        Ok(Self {
            config,
            project_root,
        })
    }

    pub fn run(&self, command: &str) -> Result<String> {
        match command {
            "hosts" => self.generate_hosts(),
            "users" => self.generate_users(),
            "network" => self.generate_network(),
            "disko" => self.generate_disko(),
            "doc" => self.generate_doc(),
            other => Err(NixError::generate(format!("Unknown command: {other}"))),
        }
    }

    // ─── hosts.nix ──────────────────────────────────────────────────────────

    fn generate_hosts(&self) -> Result<String> {
        let content = self.generate_hosts_raw()?;
        let target = self.project_root.join("var/generated/hosts.nix");
        write_and_format(&target, &content)
    }

    pub fn generate_hosts_raw(&self) -> Result<String> {
        let mut list = NixList::new();
        for host in self.config.hosts.values() {
            list.add(Box::new(build_host_attrs(host)));
        }
        Ok(format!("{GEN_FILE_HEADER}{list}"))
    }

    // ─── users.nix ──────────────────────────────────────────────────────────

    fn generate_users(&self) -> Result<String> {
        let content = self.generate_users_raw()?;
        let target = self.project_root.join("var/generated/users.nix");
        write_and_format(&target, &content)
    }

    pub fn generate_users_raw(&self) -> Result<String> {
        let mut outer = NixAttrSet::new();
        let domain = &self.config.network.config.domain;

        for user in self.config.users.values() {
            let mut attrs = NixAttrSet::new();
            let email = user
                .email
                .clone()
                .unwrap_or_else(|| format!("{}@{}", user.login, domain));

            attrs.set_int("uid", user.uid as i64);
            attrs.set_string("email", &email);
            attrs.set_string("name", &user.name);
            attrs.set_string("profile", &user.profile);
            attrs.set("groups", Box::new(NixList::from_strings(&user.groups)));

            outer.set(&user.login, Box::new(attrs));
        }

        Ok(format!("{GEN_FILE_HEADER}{outer}"))
    }

    // ─── network.nix ────────────────────────────────────────────────────────

    fn generate_network(&self) -> Result<String> {
        let content = self.generate_network_raw()?;
        let target = self.project_root.join("var/generated/network.nix");
        write_and_format(&target, &content)
    }

    pub fn generate_network_raw(&self) -> Result<String> {
        let mut outer = NixAttrSet::new();
        outer.set_string("domain", &self.config.network.config.domain);

        for key in NETWORK_PASSTHROUGH_KEYS {
            if let Some(val) = self.config.network.config.raw.get(key) {
                outer.set(*key, array_to_nix(val));
            }
        }

        // services list (declaration order)
        let mut services_list = NixList::new();
        for svc in self.config.network.services_as_vec() {
            services_list.add(Box::new(build_service_attrs(svc)));
        }
        outer.set("services", Box::new(services_list));

        // zones (sorted by name for deterministic output)
        let mut zones_attrs = NixAttrSet::new();
        let mut zone_names: Vec<&str> = self
            .config
            .network
            .zones
            .keys()
            .map(String::as_str)
            .collect();
        zone_names.sort();
        for zone_name in zone_names {
            let zone = &self.config.network.zones[zone_name];
            zones_attrs.set(zone_name, Box::new(self.build_zone_nix(zone)));
        }
        outer.set("zones", Box::new(zones_attrs));

        Ok(format!("{GEN_FILE_HEADER}{outer}"))
    }

    fn build_zone_nix(&self, zone: &NixZone) -> NixAttrSet {
        let mut attrs = NixAttrSet::new();

        // All zone config fields go through verbatim, sorted for stability.
        let mut config_keys: Vec<&str> = zone.config.keys().map(String::as_str).collect();
        config_keys.sort();
        for key in config_keys {
            if let Some(val) = zone.config.get(key) {
                attrs.set(key, array_to_nix(val));
            }
        }
        attrs.set_string("name", &zone.name);

        if zone.is_external() {
            attrs.set(
                "tls-builder-hosts",
                Box::new(self.compute_tls_builder_hosts()),
            );
            let unbound_data = self.compute_unbound_local_data(zone);
            if !unbound_data.is_empty() {
                let mut unbound = NixAttrSet::new();
                unbound.set("local-data", Box::new(NixList::from_strings(unbound_data)));
                attrs.set("unbound", Box::new(unbound));
            }
        } else {
            attrs.set(
                "extraDnsmasqSettings",
                Box::new(self.compute_extra_dnsmasq(zone)),
            );
        }

        attrs
    }

    fn compute_extra_dnsmasq(&self, zone: &NixZone) -> NixAttrSet {
        let mut settings = NixAttrSet::new();

        // dhcp-host: sorted MAC entries (stable diffs)
        let mut dhcp_entries: Vec<&str> =
            zone.mac_addresses().values().map(String::as_str).collect();
        dhcp_entries.sort();
        settings.set("dhcp-host", Box::new(NixList::from_strings(dhcp_entries)));

        settings.set(
            "dhcp-range",
            Box::new(NixList::from_strings(&zone.dhcp_range)),
        );

        // address: /<zone.domain>/<gateway-lan-ip>
        let mut address = NixList::new();
        if let Some(gw_ip) = zone.gateway_lan_ip() {
            address.add_string(format!("/{}/{}", zone.domain(), gw_ip));
        }
        settings.set("address", Box::new(address));

        settings.set("server", Box::new(self.compute_dnsmasq_server(zone)));
        settings.set(
            "host-record",
            Box::new(NixList::from_strings(self.compute_host_records(zone))),
        );

        settings
    }

    /// dnsmasq `server=` list for a local zone:
    /// 1. external zone first (network.domain → www gateway VPN IP),
    /// 2. then every other local zone in alphabetical order, mapping the
    ///    zone's domain to its LAN gateway IP.
    fn compute_dnsmasq_server(&self, zone: &NixZone) -> NixList {
        let network_domain = &self.config.network.config.domain;
        let mut server = NixList::new();
        if let Some(www) = self.config.network.zones.get(EXTERNAL_ZONE_KEY) {
            if let Some(vpn_ip) = www.gateway_vpn_ipv4() {
                server.add_string(format!("/{network_domain}/{vpn_ip}"));
            }
        }
        let mut other_locals: Vec<&str> = self
            .config
            .network
            .zones
            .keys()
            .filter(|n| n.as_str() != EXTERNAL_ZONE_KEY && *n != &zone.name)
            .map(String::as_str)
            .collect();
        other_locals.sort();
        for other_name in other_locals {
            if let Some(other) = self.config.network.zones.get(other_name) {
                if let Some(gw_ip) = other.gateway_lan_ip() {
                    server.add_string(format!("/{}/{}", other.domain(), gw_ip));
                }
            }
        }
        server
    }

    /// Build the `host-record` list for `zone`, mirroring PHP `NixZone::buildHostRecordList`:
    /// 1. globally registered host records (one per declared host's main IP),
    /// 2. service records (zone-local, external, reverse-proxied),
    /// 3. aliases of the current zone,
    /// 4. aliases of the external (`www`) zone replicated using LOCAL IPs,
    /// 5. residual hosts from `zone.hosts()` not yet emitted (extraHosts etc.),
    /// 6. final lexicographic sort.
    fn compute_host_records(&self, zone: &NixZone) -> Vec<String> {
        let network_domain = &self.config.network.config.domain;
        let mut entries: Vec<String> = self.config.host_records.clone();

        // Step 2 — services
        for svc in self.config.network.services_as_vec() {
            let svc_zone = self.config.network.zones.get(&svc.zone);
            let host_ip = self
                .config
                .hosts
                .get(&svc.host)
                .and_then(|h| h.ip.as_deref());

            if svc.zone == EXTERNAL_ZONE_KEY {
                // www: only EXTERNAL_ACCESS services are reachable from the LAN.
                if EXTERNAL_ACCESS_SERVICES.contains(&svc.name.as_str()) {
                    if let Some(ip) = host_ip {
                        let fqdn = svc.fqdn(
                            svc_zone.map(|z| z.domain()).unwrap_or(network_domain),
                            network_domain,
                        );
                        entries.push(format!("{fqdn},{ip}"));
                    }
                }
            } else if let Some(svc_zone_ref) = svc_zone {
                // Reverse-proxied services share the gateway's IP; everything
                // else points at the host's own IP.
                let ip = if REVERSE_PROXY_SERVICES.contains(&svc.name.as_str()) {
                    svc_zone_ref.gateway_lan_ip().map(str::to_string)
                } else {
                    host_ip.map(str::to_string)
                };
                let fqdn = svc.fqdn(svc_zone_ref.domain(), network_domain);
                if let Some(ip) = ip {
                    if svc.zone == zone.name {
                        entries.push(format!("{},{fqdn},{ip}", svc.domain_label()));
                    } else {
                        entries.push(format!("{fqdn},{ip}"));
                    }
                }
            }
        }

        // Step 3 — aliases of the current zone
        for (host, aliases) in zone.aliases() {
            if let Some(Some(ip)) = zone.hosts().get(host) {
                for alias in aliases {
                    entries.push(format!("{alias},{alias}.{},{ip}", zone.domain()));
                }
            }
        }

        // Step 4 — www aliases replicated with LOCAL IP (PHP looks up
        // `$this->hosts[$host]` — the current zone's hosts, not www's).
        if let Some(www) = self.config.network.zones.get(EXTERNAL_ZONE_KEY) {
            for (host, aliases) in www.aliases() {
                if let Some(Some(ip)) = zone.hosts().get(host) {
                    for alias in aliases {
                        entries.push(format!("{alias},{alias}.{network_domain},{ip}"));
                    }
                }
            }
        }

        // Step 5 — residual hosts (PHP checks `explode(',', $record)[0]` for
        // already-emitted shortnames; reproduce that contract here).
        let already: std::collections::HashSet<String> = entries
            .iter()
            .filter_map(|e| e.split(',').next().map(str::to_string))
            .collect();
        let mut residual: Vec<(&String, &String)> = zone
            .hosts()
            .iter()
            .filter_map(|(h, ip)| ip.as_ref().map(|i| (h, i)))
            .filter(|(h, _)| !already.contains(h.as_str()))
            .collect();
        residual.sort_by(|a, b| a.0.cmp(b.0));
        for (host, ip) in residual {
            entries.push(format!("{host},{host}.{},{ip}", zone.domain()));
        }

        entries.sort();
        entries
    }

    /// `tls-builder-hosts`: every non-global LAN service exposed via TLS,
    /// formatted as `<service-domain>.<zone-domain>`.
    fn compute_tls_builder_hosts(&self) -> NixList {
        let mut list = NixList::new();
        for svc in self.config.network.services_as_vec() {
            if svc.zone == EXTERNAL_ZONE_KEY || svc.global {
                continue;
            }
            if let Some(svc_zone) = self.config.network.zones.get(&svc.zone) {
                list.add_string(format!("{}.{}", svc.domain_label(), svc_zone.domain()));
            }
        }
        list
    }

    /// Unbound `local-data` block for the www zone — synthesises A records for
    /// every global service so the upstream resolver answers with the VPN IP.
    fn compute_unbound_local_data(&self, www_zone: &NixZone) -> Vec<String> {
        let network_domain = &self.config.network.config.domain;
        let Some(vpn_ip) = www_zone.gateway_vpn_ipv4() else {
            return vec![];
        };
        let mut entries = vec![];
        for svc in self.config.network.services_as_vec() {
            if svc.zone != EXTERNAL_ZONE_KEY || !svc.global {
                continue;
            }
            if EXTERNAL_ACCESS_SERVICES.contains(&svc.name.as_str()) {
                continue;
            }
            entries.push(format!(
                "\"{}.{}. IN A {vpn_ip}\"",
                svc.domain_label(),
                network_domain
            ));
        }
        entries.sort();
        entries
    }

    // ─── disko ──────────────────────────────────────────────────────────────

    /// For each host with a disko profile, lay down (idempotently) the four
    /// machine files under `usr/machines/<host>/`. Only `generated-configuration.nix`
    /// is regenerated on every run; the rest are seeded once and then owned
    /// by the user.
    fn generate_disko(&self) -> Result<String> {
        let template_src = self
            .project_root
            .join("dnf/hosts/templates/usr-machines-default.nix");

        for host in self.config.hosts.values() {
            let Some(ref profile_path) = host.disko.profile else {
                continue;
            };
            let machine_dir = self.project_root.join("usr/machines").join(&host.hostname);
            std::fs::create_dir_all(&machine_dir)?;

            seed_if_missing(&machine_dir.join("default.nix"), || {
                std::fs::copy(&template_src, machine_dir.join("default.nix")).map(|_| ())
            })?;
            seed_if_missing(&machine_dir.join("hardware-configuration.nix"), || {
                std::fs::write(machine_dir.join("hardware-configuration.nix"), "{}")
            })?;
            seed_if_missing(&machine_dir.join("disko.nix"), || {
                std::fs::copy(
                    self.project_root.join(profile_path),
                    machine_dir.join("disko.nix"),
                )
                .map(|_| ())
            })?;

            // generated-configuration.nix: always (re)written from the host's
            // disko config plus a few flags inferred from the disko file.
            let disko_dst = machine_dir.join("disko.nix");
            let disko_content = std::fs::read_to_string(&disko_dst)?;
            let body = build_generated_conf_body(&host.disko, &disko_content);
            let content = format!("{GEN_FILE_HEADER}{{lib,...}}:{{{body}}}");
            write_and_format(&machine_dir.join("generated-configuration.nix"), &content)?;
        }
        Ok(String::new())
    }

    // ─── docs ───────────────────────────────────────────────────────────────

    fn generate_doc(&self) -> Result<String> {
        crate::mdx_generator::generator::generate(&self.project_root, false)
    }
}

// ─── per-host hosts.nix builder ────────────────────────────────────────────

/// Build one entry of the `hosts.nix` list — the full data structure shared
/// with the rest of the framework (modules, flake, colmena, etc.).
fn build_host_attrs(host: &Host) -> NixAttrSet {
    let mut attrs = NixAttrSet::new();

    attrs.set_string("hostname", &host.hostname);
    attrs.set_string("zone", &host.zone);
    attrs.set_string("fqdn", format!("{}.{}", host.hostname, host.zone_domain));
    attrs.set_string("name", &host.name);
    attrs.set_string("profile", &host.profile);

    if let Some(ip) = &host.ip {
        attrs.set_string("ip", ip);
    }
    if let Some(vpn_ip) = &host.vpn_ip {
        attrs.set_string("vpnIp", vpn_ip);
    }
    if let Some(arch) = &host.arch {
        attrs.set_string("arch", arch);
    }

    attrs.set_string("zoneDomain", &host.zone_domain);
    attrs.set_string("networkDomain", &host.network_domain);

    attrs.set("groups", Box::new(NixList::from_strings(&host.groups)));

    // features: key → value (defaults to the host's zone name)
    let mut features = NixAttrSet::new();
    for (k, v) in &host.features {
        features.set_string(k, v);
    }
    attrs.set("features", Box::new(features));

    attrs.set("users", Box::new(NixList::from_strings(&host.users)));
    attrs.set("colmena", Box::new(build_colmena(host)));
    attrs.set("services", Box::new(build_host_services(&host.services)));

    attrs
}

/// `colmena.deployment.tags` aggregates host-tagged metadata: explicit tags,
/// group/feature/user/zone derivations.
fn build_colmena(host: &Host) -> NixAttrSet {
    let mut tags = NixList::new();
    for t in &host.tags {
        tags.add_string(t);
    }
    for g in &host.groups {
        tags.add_string(format!("group-{g}"));
    }
    for k in host.features.keys() {
        tags.add_string(format!("feature-{k}"));
    }
    for u in &host.users {
        if u != "nix" {
            tags.add_string(format!("user-{u}"));
        }
    }
    tags.add_string(format!("zone-{}", host.zone));

    let mut deployment = NixAttrSet::new();
    deployment.set("tags", Box::new(tags));
    let mut colmena = NixAttrSet::new();
    colmena.set("deployment", Box::new(deployment));
    colmena
}

fn build_host_services(services: &IndexMap<String, ServiceParams>) -> NixAttrSet {
    let mut out = NixAttrSet::new();
    for (svc_name, params) in services {
        let mut svc = NixAttrSet::new();
        if let Some(title) = &params.title {
            svc.set_string("title", title);
        }
        if let Some(desc) = &params.description {
            svc.set_string("description", desc);
        }
        if let Some(domain) = &params.domain {
            svc.set_string("domain", domain);
        }
        if params.global {
            svc.set_bool("global", true);
        }
        out.set(svc_name, Box::new(svc));
    }
    out
}

// ─── network.nix service entry builder ──────────────────────────────────────

fn build_service_attrs(svc: &NixService) -> NixAttrSet {
    let mut attrs = NixAttrSet::new();
    attrs.set_string("name", &svc.name);
    if let Some(d) = &svc.domain {
        attrs.set_string("domain", d);
    }
    attrs.set_string("host", &svc.host);
    attrs.set_string("zone", &svc.zone);
    if let Some(t) = &svc.title {
        attrs.set_string("title", t);
    }
    if let Some(d) = &svc.description {
        attrs.set_string("description", d);
    }
    if svc.global {
        attrs.set_bool("global", true);
    }
    attrs
}

// ─── disko helpers ──────────────────────────────────────────────────────────

fn build_generated_conf_body(disko: &DiskoConfig, disko_content: &str) -> String {
    let mut body = String::new();

    for (name, device) in &disko.devices {
        body.push_str(&format!(
            "disko.devices.disk.{name}.device=lib.mkForce \"{device}\";"
        ));
    }

    if disko_content.contains("type = \"mdadm\";") {
        body.push_str("boot.swraid.enable = lib.mkForce true;");
    }

    // Honour `# NEEDEDFORBOOT:<mountpoint>;<mountpoint>` markers in disko files.
    for line in disko_content.lines() {
        if let Some(rest) = line.strip_prefix("# NEEDEDFORBOOT:") {
            for partition in rest.split(';') {
                let p = partition.trim();
                if !p.is_empty() {
                    body.push_str(&format!(
                        "fileSystems.\"{p}\".neededForBoot=lib.mkForce true;"
                    ));
                }
            }
        }
    }

    body
}

fn seed_if_missing<F>(path: &Path, write: F) -> Result<()>
where
    F: FnOnce() -> std::io::Result<()>,
{
    if path.exists() {
        return Ok(());
    }
    write()?;
    Ok(())
}

// ─── output ─────────────────────────────────────────────────────────────────

/// Write `content` to `target`, then run `nixfmt -sv` on it (best-effort —
/// formatter failures don't fail the generator).
fn write_and_format(target: &Path, content: &str) -> Result<String> {
    std::fs::write(target, content)?;
    let _ = std::process::Command::new("nixfmt")
        .arg("-sv")
        .arg(target)
        .status();
    Ok(String::new())
}
