use std::path::{Path, PathBuf};

use crate::error::{NixError, Result};
use crate::nix_generator::configuration::Configuration;
use crate::nix_generator::token::{NixAttrSet, NixList};

const GEN_FILE_HEADER: &str = "# DO NOT EDIT - this file is auto-generated by dnf-generator\n";

pub struct Generate {
    config: Configuration,
    project_root: PathBuf,
}

impl Generate {
    pub fn new(main_yaml: &Path, generated_yaml: &Path) -> Result<Self> {
        let project_root = main_yaml
            .parent()
            .and_then(|p| p.parent())
            .ok_or_else(|| NixError::generate("Cannot determine project root from YAML path"))?
            .to_path_buf();

        let config = Configuration::load(main_yaml, generated_yaml)?;
        Ok(Self {
            config,
            project_root,
        })
    }

    pub fn run(&self, command: &str) -> Result<String> {
        match command {
            "hosts" => self.generate_hosts(),
            "users" => self.generate_users(),
            "network" => self.generate_network(),
            "disko" => self.generate_disko(),
            "doc" => self.generate_doc(),
            other => Err(NixError::generate(format!("Unknown command: {other}"))),
        }
    }

    fn generate_hosts(&self) -> Result<String> {
        let content = self.generate_hosts_raw()?;
        let target = self.project_root.join("var/generated/hosts.nix");
        self.register_content(&target, &content, false)
    }

    pub fn generate_hosts_raw(&self) -> Result<String> {
        let mut list = NixList::new();

        for host in self.config.hosts.values() {
            let mut attrs = NixAttrSet::new();

            attrs.set_string("hostname", &host.hostname);
            attrs.set_string("zone", &host.zone);
            attrs.set_string("fqdn", format!("{}.{}", host.hostname, host.zone_domain));
            attrs.set_string("name", &host.name);
            attrs.set_string("profile", &host.profile);

            if let Some(ip) = &host.ip {
                attrs.set_string("ip", ip);
            }
            if let Some(vpn_ip) = &host.vpn_ip {
                attrs.set_string("vpnIp", vpn_ip);
            }
            if let Some(arch) = &host.arch {
                attrs.set_string("arch", arch);
            }

            attrs.set_string("zoneDomain", &host.zone_domain);
            attrs.set_string("networkDomain", &host.network_domain);

            // groups
            let mut groups = NixList::new();
            for g in &host.groups {
                groups.add_string(g);
            }
            attrs.set("groups", Box::new(groups));

            // features: key → value (zone name by default)
            let mut features = NixAttrSet::new();
            for (k, v) in &host.features {
                features.set_string(k, v);
            }
            attrs.set("features", Box::new(features));

            // users (already sorted+deduped by extract_all_users)
            let mut users = NixList::new();
            for u in &host.users {
                users.add_string(u);
            }
            attrs.set("users", Box::new(users));

            // colmena { tags = [ ... ]; }
            let mut tags = NixList::new();
            for t in &host.tags {
                tags.add_string(t);
            }
            for g in &host.groups {
                tags.add_string(format!("group-{g}"));
            }
            for k in host.features.keys() {
                tags.add_string(format!("feature-{k}"));
            }
            for u in &host.users {
                if u != "nix" {
                    tags.add_string(format!("user-{u}"));
                }
            }
            tags.add_string(format!("zone-{}", host.zone));

            let mut deployment = NixAttrSet::new();
            deployment.set("tags", Box::new(tags));
            let mut colmena = NixAttrSet::new();
            colmena.set("deployment", Box::new(deployment));
            attrs.set("colmena", Box::new(colmena));

            // services: name → { title?, description?, domain?, global? }
            let mut services = NixAttrSet::new();
            for (svc_name, params) in &host.services {
                let mut svc = NixAttrSet::new();
                if let Some(title) = &params.title {
                    svc.set_string("title", title);
                }
                if let Some(desc) = &params.description {
                    svc.set_string("description", desc);
                }
                if let Some(domain) = &params.domain {
                    svc.set_string("domain", domain);
                }
                if params.global {
                    svc.set_bool("global", true);
                }
                services.set(svc_name, Box::new(svc));
            }
            attrs.set("services", Box::new(services));

            list.add(Box::new(attrs));
        }

        Ok(format!("{GEN_FILE_HEADER}{list}"))
    }

    fn generate_users(&self) -> Result<String> {
        todo!("generate_users")
    }

    fn generate_network(&self) -> Result<String> {
        todo!("generate_network")
    }

    fn generate_disko(&self) -> Result<String> {
        todo!("generate_disko")
    }

    fn generate_doc(&self) -> Result<String> {
        todo!("generate_doc")
    }

    fn register_content(&self, target: &Path, content: &str, display: bool) -> Result<String> {
        if display {
            return Ok(content.to_string());
        }
        std::fs::write(target, content)?;
        let _ = std::process::Command::new("nixfmt")
            .arg("-sv")
            .arg(target)
            .status();
        Ok(String::new())
    }
}
